# Dockerfile
FROM node:18-alpine

# Установка рабочей директории
WORKDIR /app/frontend

# Копируем package.json и package-lock.json
COPY frontend/package.json ./

COPY frontend/package-lock.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем все файлы проекта
COPY . .

# Открываем порт, который будет использовать dev-сервер Vue.js
EXPOSE 8080

# Запускаем dev-сервер с хот релоадом
CMD ["npm", "run", "serve"]