version: '3.8'

services: 
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENV_VAR=production
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    env_file:
      - dev.env
    ports:
      - "5432:5432"