version: '3.8'

services: 

  backend:
    build: /backend
    ports:
      - "8080:8080"
    env_file:
      - dev.env
    volumes:
      - .:/app
      - ./backend:/app/backend
    depends_on:
      - postgres
      - mailpit


  postgres:
    image: postgres:15
    env_file:
      - dev.env
    ports:
      - "5432:5432"

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
  
  # frontend:
  #   build: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "8081:80" 
  #   depends_on:
  #     - backend
  #   env_file:
  #     - dev.env
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.local
    ports:
      - "3000:3000"  
    volumes:
      - .:/app
      - /app/node_modules 
    env_file:
      - dev.env 
    depends_on:
      - backend