version: '3.8'

services: 

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - dev.env
    volumes:
      - .:/app
      - ./backend:/app/backend
    depends_on:
      - postgres
      - mailpit


  postgres:
    image: postgres:15
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data: