version: '3.8'

services:
  backend:
    build: ./
    ports:
      - "8080:8080" 
    env_file:
      - dev.env 
    volumes:
      - .:/app 
    depends_on:
      - db 

  db:
    image: postgres:15
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  test-db:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"

volumes:
  db_data:
